def gv

pipeline {
    agent any

    parameters {
        string(
            name: 'VERSION',
            defaultValue: '1.1.0',
            description: 'Application version'
        )

        booleanParam(
            name: 'executeTests',
            defaultValue: true,
            description: 'Execute pipeline tests'
        )
    }

    stages {
        stage('init') {
            steps {
                script {
                    gv = load 'script.groovy'
                }
            }
        }

        stage('build') {
            steps {
                script {
                    gv.buildApp()
                }
            }
        }

        stage('test') {
            when {
                expression {
                    params.executeTests
                }
            }

            steps {
                script {
                    gv.testApp()
                }
            }
        }

        stage('deploy') {
            steps {
                script {
                    gv.deployApp()
                }
            }
        }
    }
}
